### ISSUE TITLE
TestExecutionExtraction and TestExecutionRestart tests failing

### ISSUE THREAD

**Issue by dennisvang** [JMSwag/PyUpdater#317]
### Description and cause

All tests in `TestExecutionExtraction` and `TestExecutionRestart` fail because the `deploy_dir` does not exist.

### How to reproduce

Using pyupdater 4.0-2-g7093d76:  run tests from `test_pyupdater.py` in a virtual environment (`venv`).

Verified using Python 3.8.7 on Windows 10 and Python 3.8.10 on Ubuntu 20.04.

### Notes:

- Looks like the test code hasn't changed in a long time, so I'm wondering: is this just me?
- Cause appears to be the `os.system(cmd)` call failing (returns `1`) with the following traceback from the process:
    ```
    Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    ModuleNotFoundError: No module named 'dsdev_utils'
    ```
- This `ModuleNotFoundError` smells like a `venv` issue... I'm running the tests in a `venv`, but the subshell spawned by `os.system(cmd)` does not know that... Could add a command to activate the `venv` in the subshell?

**Comment by dennisvang** [comment]
Closing this, as it's probably an issue with my local environment.
